# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/soaringmonkey13/MNR/Waterloo/3A/CO 456/ChessCurd"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/soaringmonkey13/MNR/Waterloo/3A/CO 456/ChessCurd"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/soaringmonkey13/MNR/Waterloo/3A/CO 456/ChessCurd/CMakeFiles" "/home/soaringmonkey13/MNR/Waterloo/3A/CO 456/ChessCurd//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/soaringmonkey13/MNR/Waterloo/3A/CO 456/ChessCurd/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chessCurd

# Build rule for target.
chessCurd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chessCurd
.PHONY : chessCurd

# fast build rule for target.
chessCurd/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/build
.PHONY : chessCurd/fast

Pieces/bishop.o: Pieces/bishop.cc.o
.PHONY : Pieces/bishop.o

# target to build an object file
Pieces/bishop.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/Pieces/bishop.cc.o
.PHONY : Pieces/bishop.cc.o

Pieces/bishop.i: Pieces/bishop.cc.i
.PHONY : Pieces/bishop.i

# target to preprocess a source file
Pieces/bishop.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/Pieces/bishop.cc.i
.PHONY : Pieces/bishop.cc.i

Pieces/bishop.s: Pieces/bishop.cc.s
.PHONY : Pieces/bishop.s

# target to generate assembly for a file
Pieces/bishop.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/Pieces/bishop.cc.s
.PHONY : Pieces/bishop.cc.s

Pieces/king.o: Pieces/king.cc.o
.PHONY : Pieces/king.o

# target to build an object file
Pieces/king.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/Pieces/king.cc.o
.PHONY : Pieces/king.cc.o

Pieces/king.i: Pieces/king.cc.i
.PHONY : Pieces/king.i

# target to preprocess a source file
Pieces/king.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/Pieces/king.cc.i
.PHONY : Pieces/king.cc.i

Pieces/king.s: Pieces/king.cc.s
.PHONY : Pieces/king.s

# target to generate assembly for a file
Pieces/king.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/Pieces/king.cc.s
.PHONY : Pieces/king.cc.s

Pieces/knight.o: Pieces/knight.cc.o
.PHONY : Pieces/knight.o

# target to build an object file
Pieces/knight.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/Pieces/knight.cc.o
.PHONY : Pieces/knight.cc.o

Pieces/knight.i: Pieces/knight.cc.i
.PHONY : Pieces/knight.i

# target to preprocess a source file
Pieces/knight.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/Pieces/knight.cc.i
.PHONY : Pieces/knight.cc.i

Pieces/knight.s: Pieces/knight.cc.s
.PHONY : Pieces/knight.s

# target to generate assembly for a file
Pieces/knight.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/Pieces/knight.cc.s
.PHONY : Pieces/knight.cc.s

Pieces/pawn.o: Pieces/pawn.cc.o
.PHONY : Pieces/pawn.o

# target to build an object file
Pieces/pawn.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/Pieces/pawn.cc.o
.PHONY : Pieces/pawn.cc.o

Pieces/pawn.i: Pieces/pawn.cc.i
.PHONY : Pieces/pawn.i

# target to preprocess a source file
Pieces/pawn.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/Pieces/pawn.cc.i
.PHONY : Pieces/pawn.cc.i

Pieces/pawn.s: Pieces/pawn.cc.s
.PHONY : Pieces/pawn.s

# target to generate assembly for a file
Pieces/pawn.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/Pieces/pawn.cc.s
.PHONY : Pieces/pawn.cc.s

Pieces/piece.o: Pieces/piece.cc.o
.PHONY : Pieces/piece.o

# target to build an object file
Pieces/piece.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/Pieces/piece.cc.o
.PHONY : Pieces/piece.cc.o

Pieces/piece.i: Pieces/piece.cc.i
.PHONY : Pieces/piece.i

# target to preprocess a source file
Pieces/piece.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/Pieces/piece.cc.i
.PHONY : Pieces/piece.cc.i

Pieces/piece.s: Pieces/piece.cc.s
.PHONY : Pieces/piece.s

# target to generate assembly for a file
Pieces/piece.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/Pieces/piece.cc.s
.PHONY : Pieces/piece.cc.s

Pieces/queen.o: Pieces/queen.cc.o
.PHONY : Pieces/queen.o

# target to build an object file
Pieces/queen.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/Pieces/queen.cc.o
.PHONY : Pieces/queen.cc.o

Pieces/queen.i: Pieces/queen.cc.i
.PHONY : Pieces/queen.i

# target to preprocess a source file
Pieces/queen.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/Pieces/queen.cc.i
.PHONY : Pieces/queen.cc.i

Pieces/queen.s: Pieces/queen.cc.s
.PHONY : Pieces/queen.s

# target to generate assembly for a file
Pieces/queen.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/Pieces/queen.cc.s
.PHONY : Pieces/queen.cc.s

Pieces/rook.o: Pieces/rook.cc.o
.PHONY : Pieces/rook.o

# target to build an object file
Pieces/rook.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/Pieces/rook.cc.o
.PHONY : Pieces/rook.cc.o

Pieces/rook.i: Pieces/rook.cc.i
.PHONY : Pieces/rook.i

# target to preprocess a source file
Pieces/rook.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/Pieces/rook.cc.i
.PHONY : Pieces/rook.cc.i

Pieces/rook.s: Pieces/rook.cc.s
.PHONY : Pieces/rook.s

# target to generate assembly for a file
Pieces/rook.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/Pieces/rook.cc.s
.PHONY : Pieces/rook.cc.s

board.o: board.cc.o
.PHONY : board.o

# target to build an object file
board.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/board.cc.o
.PHONY : board.cc.o

board.i: board.cc.i
.PHONY : board.i

# target to preprocess a source file
board.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/board.cc.i
.PHONY : board.cc.i

board.s: board.cc.s
.PHONY : board.s

# target to generate assembly for a file
board.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/board.cc.s
.PHONY : board.cc.s

main.o: main.cc.o
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/main.cc.s
.PHONY : main.cc.s

move.o: move.cc.o
.PHONY : move.o

# target to build an object file
move.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/move.cc.o
.PHONY : move.cc.o

move.i: move.cc.i
.PHONY : move.i

# target to preprocess a source file
move.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/move.cc.i
.PHONY : move.cc.i

move.s: move.cc.s
.PHONY : move.s

# target to generate assembly for a file
move.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/move.cc.s
.PHONY : move.cc.s

utility.o: utility.cc.o
.PHONY : utility.o

# target to build an object file
utility.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/utility.cc.o
.PHONY : utility.cc.o

utility.i: utility.cc.i
.PHONY : utility.i

# target to preprocess a source file
utility.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/utility.cc.i
.PHONY : utility.cc.i

utility.s: utility.cc.s
.PHONY : utility.s

# target to generate assembly for a file
utility.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessCurd.dir/build.make CMakeFiles/chessCurd.dir/utility.cc.s
.PHONY : utility.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chessCurd"
	@echo "... Pieces/bishop.o"
	@echo "... Pieces/bishop.i"
	@echo "... Pieces/bishop.s"
	@echo "... Pieces/king.o"
	@echo "... Pieces/king.i"
	@echo "... Pieces/king.s"
	@echo "... Pieces/knight.o"
	@echo "... Pieces/knight.i"
	@echo "... Pieces/knight.s"
	@echo "... Pieces/pawn.o"
	@echo "... Pieces/pawn.i"
	@echo "... Pieces/pawn.s"
	@echo "... Pieces/piece.o"
	@echo "... Pieces/piece.i"
	@echo "... Pieces/piece.s"
	@echo "... Pieces/queen.o"
	@echo "... Pieces/queen.i"
	@echo "... Pieces/queen.s"
	@echo "... Pieces/rook.o"
	@echo "... Pieces/rook.i"
	@echo "... Pieces/rook.s"
	@echo "... board.o"
	@echo "... board.i"
	@echo "... board.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... move.o"
	@echo "... move.i"
	@echo "... move.s"
	@echo "... utility.o"
	@echo "... utility.i"
	@echo "... utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

